apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: admin-database
  template:
    metadata:
      labels:
        component: admin-database
    spec:
      volumes:
        - name: admin-storage
          persistentVolumeClaim:
            claimName: admin-database-persistent-volume-claim
      containers:
        - name: admin-database
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: admin-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: PGPASSWORD
            - name: POSTGRES_DB
              value: Admin
            - name: POSTGRES_USER
              value: postgres
