apiVersion: v1
kind: Service
metadata:
  name: admin-database-cluster-ip-service
spec: 
  type: ClusterIP
  selector:
    component: admin-database
  ports:
    - port: 5432
      targetPort: 5432