apiVersion: v1
kind: Service
metadata:
  name: admin-consumer-nodeport-service
spec:
  selector:
    component: admin-consumer
  type: NodePort
  ports:
    - port: 80
      targetPort: 8088
