apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: admin
  template:
    metadata:
      labels:
        component: admin
    spec:
      containers:
        - name: admin
          image: nitheeshkumarkambala/admin
          ports:
            - containerPort: 8093
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: admin-database-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: Admin
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: PGPASSWORD