apiVersion: v1
kind: Service
metadata:
  name: appointment-database-cluster-ip-service
spec: 
  type: ClusterIP
  selector:
    component: appointment-database
  ports:
    - port: 5432
      targetPort: 5432