apiVersion: v1
kind: Service
metadata:
  name: doctor-consumer-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: doctor-consumer
  ports:
    - port: 8087
      targetPort: 8087