apiVersion: v1
kind: Service
metadata:
  name: doctor-consumer-nodeport-service
spec:
  selector:
    component: doctor-consumer
  type: NodePort
  ports:
    - port: 80
      targetPort: 8087
