apiVersion: v1
kind: Service
metadata:
  name: feedback-database-cluster-ip-service
spec: 
  type: ClusterIP
  selector:
    component: feedback-database
  ports:
    - port: 5432
      targetPort: 5432