apiVersion: v1
kind: Service
metadata:
  name: patient-consumer-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: patient-consumer
  ports:
    - port: 8089
      targetPort: 8089