apiVersion: v1
kind: Service
metadata:
  name: user-database-cluster-ip-service
spec: 
  type: ClusterIP
  selector:
    component: user-database
  ports:
    - port: 5432
      targetPort: 5432