apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
  template:
    metadata:
      labels:
        component: user
    spec:
      containers:
        - name: user
          image: nitheeshkumarkambala/user
          ports:
            - containerPort: 8091
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: user-database-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: User
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-credentials
                  key: PGPASSWORD
