apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user-database
  template:
    metadata:
      labels:
        component: user-database
    spec:
      volumes:
        - name: user-storage
          persistentVolumeClaim:
            claimName: user-database-persistent-volume-claim
      containers:
        - name: user-database
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-credentials
                  key: PGPASSWORD
            - name: POSTGRES_DB
              value: User
            - name: POSTGRES_USER
              value: postgres
